# manually run: trunk build

FROM docker.io/svenstaro/miniserve:alpine
COPY public public
USER 1000:1000
EXPOSE 443
ENTRYPOINT ["/app/miniserve", "public", "--index", "index.html", "--spa", "-i", "::", "-p", "443", "-t", "Tyme"]
